#notarispro
notarispro_nginx:
    build: ./nginx
    ports:
        - 8300:80
    links:
        - notarispro_php
    volumes_from:
        - notarispro
notarispro_php:
    build: ./php/
    expose:
        - 9000
    volumes_from:
        - notarispro
#    command: sh /var/www/html/composer.sh
notarispro:
    image: php:7.0-fpm
    volumes:
        - ./apps:/var/www/html
    command: "true"
